### ISSUE TITLE
get_or_insert

### ISSUE THREAD

**Issue by steveklabnik** [Robbepop/cionc#8]
> ```
> // This code should work (in my opinion), but the borrow checker prevents it
> ```
> 
>    // from compiling because of an immutable borrow of self.
>    // How can I fix things like that in general?
>    // I guess I have to restructure my project or at least how this type works.

The way around this is the Entry API. Here it is on HashMap: http://doc.rust-lang.org/std/collections/struct.HashMap.html#method.entry

**Comment by Robbepop** [comment]
I didn't know much about the Entry API but I found out that it only works on value types which is a known problem.
So in order to simulate a HashSet<String> I need to create a HashMap<String,String> with the current API of the standard.
This works and should be better than my current approach with Vec though ... ;)
