### ISSUE TITLE
CharProperties

### ISSUE THREAD

**Issue by steveklabnik** [Robbepop/cionc#9]
> // However, I have already read that it is bad code smell in Rust to implement
> // custom traits for native types - I am asking why and what should I do instead?
> // Create a wrapper for char and implement these methods there?

A wrapper is one way to do it, but I believe char already implements all of these methods, so you should be able to just use them.

**Comment by Robbepop** [comment]
Thank you for hinting me to these standard defined methods - I didn't know about them.

I don't know if this is just premature optimization but the standard library defined methods work on unicode while my types only work on ASCII types. Besides that I have further restrictions. For example are hexdec literals only consisting of characters A-Z but not a-z (no lower-case). This could be fixed with an additional check for is_lower_case() but I think this is unnessesary.
Also I don't want to accept unicode characters as identifiers as in my honest opinion no sane developer should ever do this anyways.
I could always check is_ascii (or sth. like that) but this is also unnessesary with my current definitions.

Maybe I should go with a wrapper struct then ...
Or maybe you can convince me that my approach is wrong?

**Comment by steveklabnik** [comment]
Well, if you're only dealing with ASCII, then you should probably be working on `u8`, not `char`. You're gonna be wasting three bytes for little reason.

**Comment by Robbepop** [comment]
Oh that could be damn right!
My intention was that I don't want to use unicode for the code but just for the character- and string-literals. Maybe this could be a bad design decision, I have to rethink this again.
